
export const GET_ALL_NOTIFI = 'GET_ALL_NOTIFI';
export const SHOW_ALL_NOTIFI = 'SHOW_ALL_NOTIFI';
export const DELETE_NOTIFI = 'DELETE_NOTIFI';
export const CALL_DELETE_SUCCESS = 'CALL_DELETE_SUCCESS';
export const ADD_NOTIFI = 'ADD_NOTIFI';
export const ADD_NOTIFI_SUCCESS = 'ADD_NOTIFI_SUCCESS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUSSESS = 'DELETE_PRODUCT_SUSSESS';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const ADD_NOTIFI_ERORR = 'ADD_NOTIFI_ERORR';



