
export const SHOW_ALL_COMMENT = 'SHOW_ALL_COMMENT';
export const DELETE_CATE_FAIL = 'DELETE_CATE_FAIL';
export const SEARCH_NAME = 'SEARCH_NAME';
export const DELETE_CATE = 'DELETE_CATE';
export const SHOW_ALL_CATEGORIES = 'SHOW_ALL_CATEGORIES';
export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const ADD_CATEGORIES_SUCCESS = 'ADD_CATEGORIES_SUCCESS';
export const DELETE_CATE_SUSSESS = 'DELETE_CATE_SUSSESS';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';


