export const OPEN_FORM = 'OPEN_FORM';
export const EDIT_STATUS_PRODUCT = 'EDIT_STATUS_PRODUCT';
export const POST_STATUS_PRODUCT = 'POST_STATUS_PRODUCT';
export const SEARCH_NAME = 'SEARCH_NAME';
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const SHOW_ALL_PRODUCT = 'SHOW_ALL_PRODUCT';
export const ADD_PRODUCT_SUSSESS = 'ADD_PRODUCT_SUSSESS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUSSESS = 'DELETE_PRODUCT_SUSSESS';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const SHOW_GATE = 'SHOW_GATE';


