export const GET_ALL_COMMENT = 'GET_ALL_COMMENT';
export const SHOW_ALL_COMMENT = 'SHOW_ALL_COMMENT';
export const EDIT_STATUS_COMMENT = 'EDIT_STATUS_COMMENT';
export const SEARCH_NAME = 'SEARCH_NAME';
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const EDIT_SUCESS_COMMENT = 'EDIT_SUCESS_COMMENT';
export const ADD_PRODUCT_SUSSESS = 'ADD_PRODUCT_SUSSESS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUSSESS = 'DELETE_PRODUCT_SUSSESS';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const SHOW_GATE = 'SHOW_GATE';

