export const SIGNIN_REQUESTING = 'SIGNIN_REQUESTING';  
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';  
export const NOT_SIGNIN_SUCCESS = 'NOT_SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const SERVER_FAIL = 'SERVER_FAIL';
